# To access SQL At command line - $ docker exec -it jpc-database psql -U jpc

version: '3.1'

services:

  jpc:
    image: quay.io/hmpps/calculate-journey-variable-payments:latest
    container_name: jpc
    environment:
      resources.provider: "s3"
      import-files.locations: "schedule_34_locations.xlsx"
      import-files.serco-prices: "serco_prices.xlsx"
      import-files.geo-prices: "geoamey_prices.xlsx"
      export-files.template: "src/main/resources/spreadsheets/JCP_template.xlsx"
      SERVER_PORT: "8080"
      APP_DB_URL: "postgres://jpc:letmein@db:5432/jpc"
      JPC_AWS_ACCESS_KEY_ID: "localstack"
      JPC_AWS_SECRET_ACCESS_KEY: "localstack"
      JPC_BUCKET_NAME": "jpc"
      BASM_AWS_ACCESS_KEY_ID: "localstack"
      BASM_AWS_SECRET_ACCESS_KEY: "localstack"
      BASM_BUCKET_NAME: "basm"
    networks:
      - hmpps
    ports:
      - "8080:8080"
  db:
    image: postgres:latest
    container_name: jpc-database
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: jpc
      POSTGRES_USER: jpc
      POSTGRES_PASSWORD: letmein
    networks:
      - hmpps

  localstack:
    image: localstack/localstack:0.11.5
    container_name: localstack
    networks:
      - hmpps
    ports:
      - "4567-4597:4567-4597"
      - 8999:8080
    environment:
      - SERVICES=s3
      - DEBUG=${DEBUG- }
      - DATA_DIR=${DATA_DIR- }
      - DOCKER_HOST=unix:///var/run/docker.sock
      - DEFAULT_REGION=eu-west-2
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - $PWD/localstack:/docker-entrypoint-initaws.d

networks:
  hmpps:
