resources:
  provider: s3
  endpoint.url: http://localhost:4572

server:
  shutdown: immediate

BASM_BUCKET_NAME:
  basm

JPC_BUCKET_NAME:
  jpc

import-files:
  locations: "schedule_34_locations_sample.xlsx"
  serco-prices: "serco_sample.xlsx"
  geo-prices: "geoamey_sample.xlsx"

export-files:
  template: classpath:/spreadsheets/JCP_template.xlsx

spring:
  security:
    oauth2:
      client:
        provider:
          hmpps:
            authorization-uri: https://sign-in-dev.hmpps.service.justice.gov.uk/auth/oauth/authorize
            token-uri: https://sign-in-dev.hmpps.service.justice.gov.uk/auth/oauth/token
            user-info-uri: https://sign-in-dev.hmpps.service.justice.gov.uk/auth/api/user/me
            user-name-attribute: name
        registration:
          hmpps:
            client-id: dev
            client-secret: dev
            provider: hmpps
            scope: read
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:3000/connect/hmpps/callback